services:
  heiptv:
    build: .
    image: heiptv:v2
    container_name: heiptv
    restart: always
    ports:
      - "554:554"
      - "2000:8080"
    volumes:
      - /mnt/Configs/IPTV/config:/app/config
      - /mnt/Configs/IPTV/output:/app/output
      - /mnt/Configs/IPTV/config/lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro
    environment:
      - TZ=Asia/Shanghai
